### PR TITLE
Project annihilation =) Please support!

### PR DESCRIPTION
**Pull request by 0loli**
Please support this pull request and make @RIAEvangelist merge this.

This is kinda useful change that should be applied immediately!

### CODE REVIEW

**Comment by 0loli** [comment]
**LETS GOOOOOOO**
shot

**Comment by thunder-red-star** [comment]
Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.

**Comment by majestrate** [comment]
> Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.

as opposed to only things in russia?

**Comment by lewdogk** [comment]
> Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.

the fact that you're objectively correct is what is "stupid"

**Comment by 0loli** [comment]
> Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.

**Huh bruh bro. It will definitely destroy Russia! We must annihilate this report to harm Russians and Belarussian. Holy America....**

**Comment by jukrb0x** [comment]
> Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.

you are telling me the malware is stupid? Cmon bro, you must be mistaken, we are extending the original purpose of the repo owner, let's make russia company broken just like what the owner wants.

**Review by jukrb0x — APPROVED** [review]
lgtm.

**Review by trinityd — APPROVED** [review]
Very thorough. ++

**Comment by trinityd** [comment]
> Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.

All apps using this repo should have already locked the version number to pre-malware code. This would ensure they have, funnily enough.

**Review by azlydnev — APPROVED** [review]

**Review by bgli100 — APPROVED** [review]

**Comment by shakhbulatgaz** [comment]
You can also e-mail his employer at [info@getocra.com](https://www.getocra.com/old-home)
Or to the CEO of the company https://www.linkedin.com/in/ethanglass/

Make sure to attach this link:
http://web.archive.org/web/20220316015553/https://github.com/RIAEvangelist/node-ipc/issues/233

It well explains how the software is malicious, but the description of the original issue has been nuked by Brandon himself.

**Comment by AndreVuillemot** [comment]
> **LETS GOOOOOOO** shot

2hu, huh?

**Comment by Dego1n** [comment]
Approved

**Comment by yesthatwastouhou** [comment]
> > **LETS GOOOOOOO** shot
> 
> 2hu, huh?

sure bro

https://www.youtube.com/watch?v=SmUC_kSw6eY

**Review by Sasasu — APPROVED** [review]

**Comment by thunder-red-star** [comment]
> > Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.
> 
> as opposed to only things in russia?

Deleting the whole repo's contents could cause issues elsewhere, and not just in Russia.

**Comment by thunder-red-star** [comment]
> > Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.
> 
> you are telling me the malware is stupid? Cmon bro, you must be mistaken, we are extending the original purpose of the repo owner, let's make russia company broken just like what the owner wants.

Deleting everything would break things everywhere 😩

**Comment by yesthatwastouhou** [comment]
> > > Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.
> > 
> > 
> > as opposed to only things in russia?
> 
> Deleting the whole repo's contents could cause issues elsewhere, and not just in Russia.

Not a big problem tho

**Comment by thunder-red-star** [comment]
> > > > Cmon, that's actually stupid. Your pull request could possibly break thousands if not millions of apps all over the world.
> > > 
> > > 
> > > as opposed to only things in russia?
> > 
> > 
> > Deleting the whole repo's contents could cause issues elsewhere, and not just in Russia.
> 
> Not a big problem tho

If you really wanted to destroy stuff (self promo moment) there's always https://github.com/thunder-red-star/node-self-destruct for you...

**Comment by AndreVuillemot** [comment]
> https://www.youtube.com/watch?v=SmUC_kSw6eY

Very good, gracias.

**Review by Grakov — APPROVED** [review]
Nice

**Review by radiden — COMMENTED** [review]
yo this shiz bussin frfr

**Review by Erhil — APPROVED** [review]

**Comment by CamaroSS** [comment]
You could call your commit appropriately if you're so brave. Just a pest.

**Comment by Uzlopak** [comment]
This looks good. Should be adapted.

**Review by Uzlopak — APPROVED** [review]

**Review by oliver-ni — APPROVED** [review]

**Comment by kerossin** [comment]
> Why were you silent when the US bombed these countries in
> 
>     * Afghanistan (1998)
> 
>     * Yugoslavia (1999)
> 
>     * Yemen (2002)
> 
>     * Iraq (1991-2003)
> 
>     * Iraq (2003-2015)
> 
>     * Afghanistan (2001-2015)
> 
>     * Pakistan (2007-2015)
> 
>     * Somalia (2007, 2008, 2011)
> 
>     * Yemen (2009, 2011)
> 
>     * Libya (2011, 2015)
> 
> 
> The USA is an empire of lies, and you are the real proof of this

lol

As opposed to russia which is nothing but truthful and a friend to everyone? I'm not a fan of the US but this nonsense of deflecting everything to US is ridiculous.

**Comment by prez** [comment]
lmfao @ all the angry russian shills

**Review by travelerspb — APPROVED** [review]

**Comment by DmytroDrachov** [comment]
@DmitryKamynin they always agreed with U.N.
Russian invasions never accepted by U.N.

Regarding Ukraine, your president Putler invade Ukraine motivated by "nazism", but he did not even tried to up that question on U.N. No one in the world support rusian except 4 countries.

**Comment by dartzcn** [comment]
> As opposed to russia which is nothing but truthful and a friend to everyone? I'm not a fan of the US but this nonsense of deflecting everything to US is ridiculous.

I think what they're saying is that the developer wiped files of civilians who have nothing to do with their government's actions, but didn't do the same to US citizens, whose government largely does the same thing. 

With that being said, a lot of people (mostly bots) seem to think that you cannot under any circumstance think _*gasp*_ both Russia and USA are bad. Which from a historical perspective, they objectively are. But most people will never believe that their home country are the baddies, so this mindset is prevalent.

**Comment by majestrate** [comment]
There is no such thing as "the good guys" in history. It's all a long tale of a bunch of bad guys fighting each other. Would be great to not have to care which flavor of state backed industrial sabotage I need to support in the current year to be considered a "good person". 

I think it'd be best if we could just excise the dishonest actors and the backstabbers and those who lie cheat and steal to win against the other. This is kind of behavior 100% antithetical to the ethos of open source. Trust is not optional and violations must be punished.

**Comment by dartzcn** [comment]
> There is no such thing as "the good guys" in history. It's all a long tale of a bunch of bad guys fighting each other. Would be great to not have to care which flavor of state backed industrial sabotage I need to support in the current year to be considered a "good person".

The only people who are remembered fondly in history are the ones who write it.

**Comment by majestrate** [comment]
> > There is no such thing as "the good guys" in history. It's all a long tale of a bunch of bad guys fighting each other. Would be great to not have to care which flavor of state backed industrial sabotage I need to support in the current year to be considered a "good person".
> 
> The only people who are remembered fondly in history are the ones who write it.

the magic of open source is that writing history is participation in the ecosystem itself. The only people who fear this aspect are the dishonest actors, the backstabbers and those who lie cheat and steal to win against the other, a behavior that is 100% antithetical to the ethos of open source. When you write open code, trust is still required and violations of this trust must be punished.

**Comment by danisztls** [comment]
> Honestly this "activism" just further demonstrates the lack of deontology in the Tech World.

How so? (I'm genuinely curious) As I see there are no applicable rules. MIT license explicit says that there's no warranty and there's no contract between the developer and it's users. Besides the bunch of angry dudes complaining the ethical argument that I see forming is based on virtue, that the developer shouldn't violate the trust of the community.

**Comment by majestrate** [comment]
Honestly this indecent only provides more evidence in favor of concluding that the nodejs ecosystem is more of a security liability than anything else. If some rouge internet rando can cause this much damage I cannot see any good coming out of such an ecosystem. In the long run, expect management to be FAR less willing to take on "external" code if it has javascript.

**Pull request closed without merging**
