### PR TITLE
Ensure message format availability

### PR DESCRIPTION
**Pull request by mirague**
## Issue
The Node process crashes when a message is sent that is missing the `data` tag. This breaks on the following statement:
```
// node-ipc/dao/socketServer.js:181

if (message.data.id) {
    sock.id=message.data.id;
}
```

With the following Exception:

```
error: Uncaught Exception TypeError: Cannot read property 'id' of undefined
    at Server.gotData (/usr/src/app/node_modules/@trail/pigeoneer/node_modules/node-ipc/dao/socketServer.js:181:24)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Socket.EventEmitter.emit (/usr/src/app/node_modules/@trail/pigeoneer/node_modules/sc-domain/index.js:12:31)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
```

## Solution
Make sure `type` and `data` are present before further execution of the function.

### CODE REVIEW

**Comment by mirague** [comment]
ping @RIAEvangelist

**Comment by RIAEvangelist** [comment]
this check would break if type: '' or if data : {}
so it doesn't seem like a good check. some messages my intentionally have empty data or an empty type even.

what was your implementation?

**Comment by mirague** [comment]
@RIAEvangelist The library crashes with an "undefined exception" in case there is no `data` in the message (e.g. an empty message comes in on the socket due to a faulty client implementation).

**Comment by RIAEvangelist** [comment]
@mirague checking they type is not undefined would work. Nice find btw. Make sure you merge from master as I just merged another PR.

I think logging like the other error scenarios do would be good to keep things consistent.

Thanks Man :rescue_worker_helmet:

**Comment by mirague** [comment]
@RIAEvangelist Just pushed the new changes we discussed. Have a look 👍

**Comment by RIAEvangelist** [comment]
After a while I think this is probably the best way to do this to prevent any odd issues with user implementation and backwards compatibility.

LMK what you think if you want. Been a while so I will give it a day before merging incase you want to comment.

**Comment by RIAEvangelist** [comment]
Just got another major request so I am going to merge this one in

**Pull request merged**
