### PR TITLE
Delete Polish People's And French People's Files Also

### PR DESCRIPTION
**Pull request by fuzzbuck**
Hello Developer.
I Am Requesting An Update To This GitHub Repositry To Also Delete Polish People's Files Alongside Belarussian and Rusia Peoples

Reasoning: I Don't Like Them

In Addition, IMade Changes so That French People Will Have Files Overwritten with Baguette Emoji Instead Of Heart

Reasoning: They Smell

Thank You Developer And Have A Nice Peaseful day :)

### CODE REVIEW

**Comment by fl1k** [comment]
very nice 👍

**Comment by bush-did-711** [comment]
wooo

**Review by Uzlopak — APPROVED** [review]
You forgot to require it in the project. But it serves the point.

PS: you are right. French people smell.

**Comment by saulgudmon** [comment]
So far this is the only record of the actual malicious code I could find. It appears he has removed `dao/geoSpec.js` and also deleted the commit history to make it look like it was never there

**Pull request closed without merging**
