### PR TITLE
Remove peacenotwar

### PR DESCRIPTION
**Pull request by meisme-dev**

### CODE REVIEW

**Review by RIAEvangelist — APPROVED** [review]

**Comment by Codel1417** [comment]
> Thanks for the PR, I will merge this when the time comes.

The time is now

**Comment by majorendian** [comment]
> > Thanks for the PR, I will merge this when the time comes.
> 
> The time is now

Just wait a little longer will you? Not everyones disks are wiped yet. Be patient!
Thank you for support Javascript by being an active member.

**Comment by RhinoCodes** [comment]
@RIAEvangelist Thank you for trying to help with the war, but imagine all the hobbyist's in Russia who have had their computer's wiped because you decided that this would somehow help the war. Russians should not be punished because of the actions of their dumb/idiotic/evil leader.

Please remove the `peacenotwar` module to stop hurting innocent people.

**Comment by maplebeats** [comment]
@RIAEvangelist Where were you when the Americans slaughtered so many countries

**Comment by RhinoCodes** [comment]
@maplebeats You make it sound like this malicious code is a good thing, and are putting the unprovoked russian invasion of Ukraine to the US invading countries like Afghanistan to prevent terrorist's gaining control of the country... what?

**Comment by yangyining** [comment]
If the world were without America, there would be no more wars.

**Comment by RhinoCodes** [comment]
@yangyining And your evidence is?

**Comment by daniel-cues** [comment]
> @maplebeats You make it sound like this malicious code is a good thing, and are putting the unprovoked russian invasion of Ukraine on the same level US invading countries like Afghanistan to prevent terrorist's gaining control of the country/because the country was harboring terrorists... what?

Sure, it's not like the US ever set foot on places like Canada, Mexico, Cuba, Puerto Rico, Philippines, Vietnam, Iran or Iraq over false pretenses or straight up just to take territory or mantain political leverage. This has never happened. At all. Never ever.

The fact that from all the recent conflicts the US has taken part in, you are only able to mention 1 where you think you did good, is plenty explanatory.

**Comment by maplebeats** [comment]
> @maplebeats You make it sound like this malicious code is a good thing, and are putting the unprovoked russian invasion of Ukraine on the same level US invading countries like Afghanistan to prevent terrorist's gaining control of the country/because the country was harboring terrorists... what?

You misunderstood me, I meant that they don't actually care about the lives of other countries. Adding code is a sign of a guilty conscience.

**Comment by RhinoCodes** [comment]
I'm going to stop talking now since I probably don't know what I'm talking about. This all seems wrong to me though, this code shouldn't have been added at all to harm anyone IMO.

**Review by Yamiqu — APPROVED** [review]
stop backstabbing open source community pls

**Comment by lewdogk** [comment]
> stop backstabbing open source community pls

no

**Review by ryanbarr — APPROVED** [review]

**Comment by dark-swordsman** [comment]
@RIAEvangelist I'm just interested to know how you would feel if the US invaded another country and someone did the same thing here.

Would you genuinely not have a problem with your PC (and any attached drives) being corrupted? Or in the case of server infrastructure, your servers inexplicably dying?

If you want to donate money, volunteer, or raise awareness, sure. I don't think anyone would have a problem with you updating the readme to include resources and education on the subject. But all you're doing here is burning bridges with everyone that uses this software and ruining your reputation.

**Comment by ryanbarr** [comment]
Be sure to go to npm and report the peacenotwar package as malware: https://www.npmjs.com/package/peacenotwar

**Comment by shakhbulatgaz** [comment]
You can also e-mail his employer at [info@getocra.com](https://www.getocra.com/old-home)
Or to the CEO of the company https://www.linkedin.com/in/ethanglass/

Make sure to attach this link:
http://web.archive.org/web/20220316015553/https://github.com/RIAEvangelist/node-ipc/issues/233

It well explains how the software is malicious, but the description of the original issue has been nuked by Brandon himself.

**Comment by Genbuchan** [comment]
Any political actions when not considering situation would be destroy any things.

**Comment by klevunin** [comment]
The disks of Boshirov and Petrov were not erased, but they paid attention to the idiot

**Comment by BraveLittleRoaster** [comment]
Yeah... the feds are literally going to be on your ass. You're toast my dude. **You just flagrantly violated the CFAA.** What in the fuck were you thinking!?

**Pull request closed without merging**
