### PR TITLE
feat: add emit callback

### PR DESCRIPTION
**Pull request by boluobanana**
Add callback when the client emit message success.

### CODE REVIEW

**Comment by RIAEvangelist** [comment]
I think this is best left to the codebase that uses `node-ipc` to implement.

Can explain why this belongs as a part of the core? Like some examples of where this sort of behavior is required would be good. Thanks.

**Comment by boluobanana** [comment]
Sometime I want to exit the client process when the last message was succeed.  

Example A: message may not send success
```
// client
client.emit("WILL_CLOSE", "the last message"); // this message maybe not send success
process.exit(0); 
```

If the client.emit with the callback. It will be nice 

Example B: exit when the message send success
```
// client
client.emit("WILL_CLOSE", "the last message", function () {
    process.exit(0); 
}); 

```

**Comment by RIAEvangelist** [comment]
I understand what you expect the code to do ;) This seems more like it is something that should be solved in your code. Not the module. I was asking, more specifically, if you had a reason this should be handled by the module rather than your code.
 
Wouldn't you just do this?



Example A: message may not send success
```

//bind an exit event
client.on("WILL_CLOSE",(data)=>{console.log(`got ${data} and did stuff with it`);process.exit(0)});
client.emit("WILL_CLOSE", "the last message"); 

client.on("WILL_CLOSE",(data,shouldClose)=>{console.log(`git ${data} and did stuff with it`);(shouldClose)? process.exit(0)||return false;});
client.emit("WILL_CLOSE", "the last message", true); // this message maybe not send success

client.on("EXIT",()=>{process.exit(0));
client.emit("EXIT"; 

```

**Comment by boluobanana** [comment]
My apologies. Let me explain again. In my code there are two process.
Process A is Server.
Process B is Client.
Client want to send some message to server before exit himself. But sometime server may not receive the last message, because the client not finish `emit("CLIENT_CLOSE")` before the exit.
```
// Process A Server
server.on("CLIENT_CLOSE", (socket, message) => {
// do something
})
```
```
// Process B Client
client.emit("CLIENT_CLOSE", "last message");
process.exit(0);
```

And I know what you mean as well. For now without the 'callback'. Some code after this line is work for me. But if  this module has the 'callback' will be better.  'CLIENT_CLOSE_ACK' no need anymore. Less code, less IPC.

```
// Process A Server
server.on("CLIENT_CLOSE", (socket, message) => {
    server.emit(socket, "CLIENT_CLOSE_ACK");
})
```

```
// Process B Client
client.on("CLIENT_CLOSE_ACK", () => {
    process.exit(0);
})
client.emit("CLIENT_CLOSE", "last message");
```

**Comment by RIAEvangelist** [comment]
I'm thinking the ACK is best, the callback could be confusing to people and make it easy for developers to mix callbacks and events. This could make it easy for code to behave weird.

I was considering returning a promise for this. I think it would be a better solution and keep fewer callbacks. This way you to do async-await or promise style and help developers keep their code less confusing.

What do you think?

**Pull request closed without merging**
