### PR TITLE
The world will need this open source project, It is good deeds to protest by its owner

### PR DESCRIPTION
**Pull request by jukrb0x**
I totally agree the package added earlier to this project, is very good and I like it. So I have some of my personal idea to flourish this project.

### CODE REVIEW

**Comment by LaoshuBaby** [comment]
Well done, but I think the better way is delete this evil repository because it destroy the trust between open source developers.

**Comment by ChloePrime** [comment]
Replace the sponsor link with Russia's would be better :)

**Review by ChenZheChina — APPROVED** [review]

**Comment by ChenZheChina** [comment]
The owner of this project should realize that it’s very dangerous if trust is broken. Some people just don’t know what they did is wrong until it comes to themselves.

**Review by FlickerSoul — APPROVED** [review]

**Review by shorwood — APPROVED** [review]

**Review by RIAEvangelist — CHANGES_REQUESTED** [review]
updates seem extreme for something that could be handled with dependency locking.

all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

**Comment by Darkmift** [comment]
I understand your motives but you did something without giving tought to its outcome.

Today its a message of peace,tomorrow something far more sinister.

The wake of this act is not going to lead to positive outcome...you inspired malicious ideas and you encourage hostile response.

**Comment by forthrightwit** [comment]
> I understand your motives but you did something without giving tought to its outcome.
> 
> Today its a message of peace,tomorrow something far more sinister.
> 
> The wake of this act is not going to lead to positive outcome...you inspired malicious ideas and you encourage hostile response.

I'm pretty sure the author knew full well what the outcome would be. And he doesn't care. Why should he?

At the end of the day, it's a benign protest against the Russian invasion of Ukraine. No harm done. At the same time, the Node.JS developer community is now much more aware of how naive they've been for trusting arbitrary dependencies from unknown authors.

**Comment by lewdogk** [comment]
don't worry guys, i'm halving his salary

**Comment by jukrb0x** [comment]
> I understand your motives but you did something without giving tought to its outcome.
> 
> Today its a message of peace,tomorrow something far more sinister.
> 
> The wake of this act is not going to lead to positive outcome...you inspired malicious ideas and you encourage hostile response.

haha, obviously you did not see the point of this pr, this is definitely a troll, like what the _peacenotwar_  did, and hijacking users' OneDrive that is real malicious in the first place, and like @RIAEvangelist said, users can lock up a version, you can close up this pr, right?

> updates seem extreme for something that could be handled with dependency locking.
> 
> all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.

Today you did is only adding a file to the desktop, Tomorrow something far more sinister, is that right @Darkmift ? I am your truthful believer. And What I remember is the project hijacking the users' OneDrive in the first place, how are you gonna explain that? 

> all it does is add a file to the desktop that gives a message of peace, not war, and remember to forgive. It is all also documented.
>
> feel free to lock the dep version.

see, that is your problem, as a Japanese situated in the US who must want to do something to show its antiwar emotion.

**so, it is not something like feel 'free to lock version', you give people rice and let them eat, and then you add some shit into the rice, tell people such that go to eat something else or just eat my shit. think about it, you are malicious just like Unit 731 ** It is never a proper way to protest like what you did to the opensource community, you are the Unit 731 in node community.

**Comment by dark0ghost** [comment]
After such actions, why are you better than Putin?

**Comment by devpew** [comment]
Malware maker. Shame on you.

**Pull request closed without merging**
